[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agent-mesh"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Art Morozov", email = "art.morozov@solace.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/SolaceDev/agent-mesh#readme"
Issues = "https://github.com/SolaceDev/agent-mesh/issues"
Source = "https://github.com/SolaceDev/agent-mesh"

[tool.hatch.version]
path = "src/agent_mesh/__init__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/agent_mesh tests}"

[tool.coverage.run]
source_pkgs = ["agent_mesh", "tests"]
branch = true
parallel = true
omit = [
  "src/agent_mesh/__about__.py",
]

[tool.coverage.paths]
agent_mesh = ["src/agent_mesh", "*/agent-mesh/src/agent_mesh"]
tests = ["tests", "*/agent-mesh/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
