- {{SNAKE_CASE_NAME}}_config: &gateway_interface_config
    key: "value" # Add your configuration here

- response_format_prompt: &response_format_prompt >
    Return all responses in markdown format and if the response contains a file or image, use the <{tag_prefix}file> tags with the assigned tag prefix.
    Do not return files as links or with generic <file> tags.
