- web_config: &web_config
    acknowledgement_message: "Chatbot is thinking... &#x23F3;"
    max_total_file_size: 0.5
    max_file_size: 2000 # 2GB

- response_format_prompt: &response_format_prompt >
    Return all responses in markdown format and if the response contains a file or image, use the <{tag_prefix}file> tags with the assigned tag prefix.
    Do not return files as links or with generic <file> tags.
